### ISSUE TITLE
Update NPM dependencies to latest (OSOE-952)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Orchard-Vue.js#160]
The module's NPM dependencies are outdated, and Renovate updated them. But, due to breaking changes, manual fixes are necessary.

After updating packages to minor versions, Windows builds will suffer random failures, as explained under https://github.com/Lombiq/Orchard-Vue.js/issues/162. It might be that the ESLint versions needs to be kept in sync with Node.js Extensions', see https://github.com/Lombiq/NodeJs-Extensions/issues/116.

After updating packages to major versions, you'll see errors like:

```
71>E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js:1
71>const del = require('del');
71>
71>            ^
71>
71>EXECWITHMUTEX : error [ERR_REQUIRE_ESM]: require() of ES Module E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\node_modules\.pnpm\del@8.0.0\node_modules\del\index.js from E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js not supported.
71>Instead change the require of index.js in E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js to a dynamic import() which is available in all CommonJS modules.
71>    at Object.<anonymous> (E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js:1:13) {
71>  code: 'ERR_REQUIRE_ESM'
71>}
71>
71>Node.js v20.11.0
71>EXECWITHMUTEX : error : "build:vue-sfc" exited with 1.
71>
71>
71>no-path(1,1): error 1: Command failed: pnpm build
71>E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js:1
71>const del = require('del');
71>
71>            ^
71>
71>EXECWITHMUTEX : error [ERR_REQUIRE_ESM]: require() of ES Module E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\node_modules\.pnpm\del@8.0.0\node_modules\del\index.js from E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js not supported.
71>Instead change the require of index.js in E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js to a dynamic import() which is available in all CommonJS modules.
71>    at Object.<anonymous> (E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js:1:13) {
71>  code: 'ERR_REQUIRE_ESM'
71>}
71>
71>Node.js v20.11.0
71>EXECWITHMUTEX : error : "build:vue-sfc" exited with 1.
71>
71>EXECWITHMUTEX : error : Command failed: pnpm build
71>E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js:1
71>const del = require('del');
71>
71>            ^
71>
71>EXECWITHMUTEX : error [ERR_REQUIRE_ESM]: require() of ES Module E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\node_modules\.pnpm\del@8.0.0\node_modules\del\index.js from E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js not supported.
71>Instead change the require of index.js in E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js to a dynamic import() which is available in all CommonJS modules.
71>    at Object.<anonymous> (E:\ShortPath\OSOCE4\src\Modules\Lombiq.VueJs\Lombiq.VueJs\Assets\Scripts\helpers\vue-sfc-compiler-pipeline.js:1:13) {
71>  code: 'ERR_REQUIRE_ESM'
71>}
71>
71>Node.js v20.11.0
71>EXECWITHMUTEX : error : "build:vue-sfc" exited with 1.
71>
71>    at ChildProcess.exithandler (node:child_process:422:12)
71>    at ChildProcess.emit (node:events:518:28)
71>    at maybeClose (node:internal/child_process:1105:16)
71>    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

- [x] Open an issue branch from the branch of https://github.com/Lombiq/Orchard-Vue.js/pull/161, fix the above-mentioned Windows build issues.
- [x] Check all updated dependencies: Are they actually all needed?
- [x] Merge from https://github.com/Lombiq/Orchard-Vue.js/pull/159, fix any compatibility issues.
- [x] Merge from https://github.com/Lombiq/Orchard-Vue.js/pull/168, fix any compatibility issues.
- [x] Remove the temporary "All packages" group from _renovate.json5_.

After merging the issue branch, the Renovate PRs should close themselves.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-952)

**Comment by Piedone** [comment]
Maybe you're interested @sarahelsaig?

**Comment by Piedone** [comment]
@sarahelsaig?

**Comment by Piedone** [comment]
@sarahelsaig?

**Comment by sarahelsaig** [comment]
I will check it out soon, probably early next week.

**Comment by Piedone** [comment]
Thanks!

**Comment by sarahelsaig** [comment]
> It might be that the ESLint versions needs to be kept in sync with Node.js Extensions'

It's because Renovate wanted to update to the next major version (ESLint v9) that has a breaking change. This should be handled in https://github.com/Lombiq/NodeJs-Extensions/issues/116 instead, I have added relevant info there and reverted ESLint to the version used there. Ideally linting script should be moved into NE so dependencies don't need to be synchronized.
